name: Node CI

on:
  push:
    branches: 
      - master
    

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
      
    - name: prepare release
      run: |
        npm install
        npm run release
      env:
        CI: true
    - name: set environment variables
      uses: allenevans/set-env@v1.0.0
      with:
        PACKAGE_VERSION : ${{ $(node -p -e "require('./package.json').version") }}

    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v${ PACKAGE_VERSION }
        release_name: ${PACKAGE_VERSION}
        draft: false
        prerelease: false
